[package]
name = "ramws"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ramws-core = { path = "../ramws-core" }
toml.workspace = true
walkdir.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
tempfile.workspace = true

[lints]
workspace = true
